### ISSUE TITLE
Test 943110-4 from coreruleset is not passing

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#167]
It's failing go-ftw tests. It requires more research.

```yaml
- test_title: 943110-4
    desc: Session Fixation Attack (943110) from old modsec regressions
    stages:
      - stage:
          input:
            dest_addr: 127.0.0.1
            headers:
              Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
              Accept-Encoding: gzip, deflate
              Accept-Language: zh-sg
              Content-Type: application/x-www-form-urlencoded
              Host: localhost
              Referer: http://localhost/test
              Keep-Alive: '300'
              Proxy-Connection: keep-alive
              User-Agent: OWASP ModSecurity Core Rule Set
            method: GET
            port: 80
            uri: /login.php?jsessionid=74B0CB414BD77D17B5680A6386EF1666
            version: HTTP/1.1
          output:
            no_log_contains: id "943110"
```
