### ISSUE TITLE
Failed to compile CRS rules v3.3.4 with coraza v2

### ISSUE THREAD

**Issue by Barnoux** [corazawaf/coraza#509]
Hello :)

## Description

When i want to build coraza with docker as a caddy module i have a compile errors.
When you looked at the rules that are not comiling the commentary of OWASP tells us that it doesn't support RE2 regex. I know that coraza use RE2.

### Steps to reproduce

I'm using coraza WAF as a caddy module, the purpose is to used coraza to protect my vaultwarden instance from web app attack.
All the containers are running on a Rapsberry pi 4 with Ubuntu "20.04.5 LTS (Focal Fossa)"

this is the caddyfile:
```
{
   order coraza_waf first
}
{$DOMAIN}:443 {
   log {
      level INFO
      output file /var/log/caddy/access.log
   }
   coraza_waf {
      include /ruleset/coraza.conf
      include /ruleset/sites/*.conf
      include /ruleset/coreruleset/rules/*.conf
   }

   tls {$EMAIL}

   encode gzip

   header {
      Strict-Transport-Security "max-age=15768000;"
      X-XSS-Protection "1; mode=block"
      Referrer-Policy "no-referrer" 
      X-Content-Type-Options "nosniff"
      X-Frame-Options "SAMEORIGIN"
      X-Robots-Tag "none"
      -Server
   }

   @insecureadmin {
      not remote_ip 192.168.0.0/16 172.16.0.0/12 10.0.0.0/8
      path /admin*
   }
   redir @insecureadmin /
   reverse_proxy /notifications/hub vaultwarden:3012

   reverse_proxy vaultwarden:60278 {
      trusted_proxies private_ranges
      header_up X-Real-IP {remote_host}
   }
}

```
this is the DockerFile that i used:
```
FROM caddy:builder AS builder
RUN xcaddy build --with github.com/corazawaf/coraza-caddy

FROM caddy:latest
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
RUN mkdir /coraza && touch /coraza/Caddyfile
WORKDIR /srv
CMD ["/usr/bin/caddy", "run", "--config", "/coraza/Caddyfile", "--adapter", "caddyfile", "--watch"]
```

In the docker compose file the service proxy look like this:
```
  proxy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    depends_on:
      - "vaultwarden"
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./caddy/Caddyfile:/coraza/Caddyfile
      - ./caddy/ruleset:/ruleset
      - logs:/var/log/caddy
      - caddy_data:/data
      - caddy_config:/config
    environment:
      DOMAIN: "https://vaultwarden.one4all.icu"
      EMAIL: "bbarnoux@gmail.com"
      ACME_AGREE: "true"
    networks:
        - frontend
```
### Expected result

The docker service "proxy" should be up and running and not exited afte the compile error.

### Actual result

Error: loading initial config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'waf': provision http.handlers.waf: failed to compile rule (error parsing regexp: invalid or unsupported Perl syntax: `(?<`): FILES_NAMES|FILES "@rx (?<!&(?:[aAoOuUyY]uml)|&(?:[aAeEiIoOuU]circ)|&(?:[eEiIoOuUyY]acute)|&(?:[aAeEiIoOuU]grave)|&(?:[cC]cedil)|&(?:[aAnNoO]tilde)|&(?:amp)|&(?:apos));|['\"=]" "id:920120,phase:2,block,t:none,t:urlDecodeUni,msg:'Attempted multipart/form-data bypass',logdata:'%{MATCHED_VAR}',tag:'application-multi',tag:'language-multi',tag:'platform-multi',tag:'attack-protocol',tag:'paranoia-level/1',tag:'OWASP_CRS',tag:'capec/1000/210/272',ver:'OWASP_CRS/3.3.4',severity:'CRITICAL',setvar:'tx.anomaly_score_pl1=+%{tx.critical_anomaly_score}'"

Regards,

BBA
