### ISSUE TITLE
Failing to detect when the payload contains single byte or alternate utf-8 encoding

### ISSUE THREAD

**Issue by soujanyanmbri** [corazawaf/coraza#688]
## Description

Coraza doesn't detect the attacks when the payload contains single byte or alternate utf-8 encoding. 

### Steps to reproduce

Test Case 1: 
```
test_title: 941310-1
desc: Positive test using single byte
stages:
  - stage:
      input:
        dest_addr: 127.0.0.1
        headers:
          Host: localhost
          Content-Type: "application/x-www-form-urlencoded; charset=us-ascii"
          User-Agent: OWASP ModSecurity Core Rule Set
          Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
        method: POST
        port: 80
        uri: /
        data: var=\xbcscript\xbealert(\xa2XSS\xa2)\xbc/script\xbe
output:
  log_contains: id "941310"
```
Test Case 2: 
``` 
test_title: 941310-3
desc: Positive test using alternate utf-8
stages:
  - stage:
      input:
        dest_addr: 127.0.0.1
        headers:
          Host: localhost
          Content-Type: "application/x-www-form-urlencoded; charset=us-ascii"
          User-Agent: OWASP ModSecurity Core Rule Set
          Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
        method: POST
        port: 80
        uri: /
        data: var=\xd0\xbcscript\xd0\xbealert(\xc2\xa2XSS\xc2\xa2)\xd0\xbc/script\xd0\xbe
output:
  log_contains: id "941310"
```
### Expected result

"id: 941310, rule_msg: US-ASCII Malformed Encoding XSS Filter - Attack, match_msg: Matched Data: ¼script¾ found within ARGS:var: ¼script¾alert(¢xss¢)¼"

"id: 941310, rule_msg: US-ASCII Malformed Encoding XSS Filter - Attack, match_msg: Matched Data: ¼scriptо found within ARGS:var: мscriptоalert(¢xss¢)м/script"

### Actual result
Coraza does not detect it.
